image: docker:24.0.5 

services:
  - docker:24.0.5-dind 

stages:
  - build-image
  - check
  - test

check_workspace:
  stage: check
  tags:
    - ansible
  script:
    - cargo check --release

lint_workspace:
  stage: check
  tags:
    - ansible
  script:
    - cargo clippy --release -- -D warnings

format_workspace:
  stage: check
  tags:
    - ansible
  script:
    - cargo fmt --all --check

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - public/


